# Jekyll site settings
title: Implementator
email: fs222vr@student.lnu.se
description: Fredrik Sundberg / fs222vr 2018
baseurl: ""
url: "http://theted.github.io"
github_username:  theted
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.png
